builds:
  - main: ./cmd/repl/
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
changelog:
  sort: desc
brews:
  - name: repl-go
    tap:
      owner: citizen428
      name: homebrew-tap
    homepage: "https://github.com/citizen428/repl"
    description: "Add more read-eval-print-love in your life"
    license: "MIT"
